// Package kongshared provides shared functions for kong services
package kongshared

// DB constant values
const(
	DB_USER_STATUS_ACTIVE = "ACTIV"
	DB_USER_STATUS_BLOCKED = "BLOCK"
	DB_USER_STATUS_PURGED = "PURGE"

	DB_ACCOUNT_GROUP_STATUS_ACTIVE = "ACTIV"
	DB_ACCOUNT_GROUP_STATUS_BLOCKED = "BLOCK"
	DB_ACCOUNT_GROUP_STATUS_PURGED = "PURGE"

	DB_ACCOUNT_STATUS_ACTIVE = "ACTIV"
	DB_ACCOUNT_STATUS_BLOCKED = "BLOCK"
	DB_ACCOUNT_STATUS_PURGED = "PURGE"
)